# use Ganache's forked mainnet mode as the default network
networks:
  default: kovan

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - ERC20
